---
title: Recoding Data
author: R Package Build
date: '2022-02-23'
slug: recoding-data
categories: []
tags: []
---
# Call libraries
```{r}
library(readxl)
```
# Get Data
```{r}
rel_inc <- read_excel("data/relig-income.xlsx")
```

# Rename Columns
```{r}
rel_inc %>%
  rename( 
    religion = `Religious tradition`, 
    n = `Sample Size` 
  )
```
# Pivot Longer
```{r}
rel_inc %>%
  rename(
    religion = `Religious tradition`,
    n = `Sample Size`
  ) %>%
  pivot_longer( 
    cols = -c(religion, n),   # all but religion and n 
    names_to = "income",  
    values_to = "proportion" 
  )
```
# Calculate Frequencies
```{r}
rel_inc %>%
  rename(
    religion = `Religious tradition`,
    n = `Sample Size`
  ) %>%
  pivot_longer(
    cols = -c(religion, n), 
    names_to = "income", 
    values_to = "proportion"
  ) %>%
  mutate(frequency = round(proportion * n))
```

# Save the Data
```{r}
rel_inc_long <- rel_inc %>% 
  rename(
    religion = `Religious tradition`,
    n = `Sample Size`
  ) %>%
  pivot_longer(
    cols = -c(religion, n), 
    names_to = "income", 
    values_to = "proportion"
  ) %>%
  mutate(frequency = round(proportion * n))
```

# Create Barplot
```{r}
ggplot(rel_inc_long, aes(y = religion, x = frequency)) +
  geom_col()
```
# Recode "Religion" column
```{r}
rel_inc_long <- rel_inc_long %>%
  mutate(religion = case_when(
    religion == "Evangelical Protestant"           ~ "Ev. Protestant",
    religion == "Historically Black Protestant"    ~ "Hist. Black Protestant",
    religion == 'Unaffiliated (religious "nones")' ~ "Unaffiliated",
    TRUE                                           ~ religion
  ))
ggplot(rel_inc_long, aes(y = religion, x = frequency)) +
  geom_col()
```

# Reverse Religion Order
```{r}
rel_inc_long <- rel_inc_long %>%
  mutate(religion = fct_rev(religion))
ggplot(rel_inc_long, aes(y = religion, x = frequency)) +
  geom_col()
```
# Include income as fill
```{r}
ggplot(rel_inc_long, aes(y = religion, x = frequency, fill = income)) + 
  geom_col()

```
# Fill bars
```{r}
ggplot(rel_inc_long, aes(y = religion, x = frequency, fill = income)) +
  geom_col(position = "fill")
```

## Change Colors
```{r}
ggplot(rel_inc_long, aes(y = religion, x = frequency, fill = income)) +
  geom_col(position = "fill") +
  scale_fill_viridis_d()
```

## Change Theme
```{r}
ggplot(rel_inc_long, aes(y = religion, x = frequency, fill = income)) +
  geom_col(position = "fill") +
  scale_fill_viridis_d() +
  theme_minimal()
```
## Move legend
```{r}
ggplot(rel_inc_long, aes(y = religion, x = frequency, fill = income)) +
  geom_col(position = "fill") +
  scale_fill_viridis_d() +
  theme_minimal() +
  theme(legend.position = "bottom")
```
## Adjust Legend Appearance
```{r}
ggplot(rel_inc_long, aes(y = religion, x = frequency, fill = income)) +
  geom_col(position = "fill") +
  scale_fill_viridis_d() +
  theme_minimal() +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(nrow = 2, byrow = TRUE))
```



