---
title: Palmer Penguins Visualizations
author: R package build
date: '2022-02-09'
slug: palmer-penguins
categories:
  - R
tags:
  - Penguins
  - GGPLOT2
---

# Palmer Penguins

Measurements for penguin species, island in **Palmer Archipelago**, size (flipper length, body mass, bill dimensions), and sex.

#Calling Libraries
```{r message=FALSE}
library(tidyverse)
library(palmerpenguins)
```
# Glimpse
```{r}
glimpse(penguins)
```
# Scatterplot
```{r}
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     colour = species)) +
  geom_point() +
  labs(title = "Bill depth and length",
       subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
       x = "Bill depth (mm)", y = "Bill length (mm)",
       colour = "Species",
       caption = "Source: Palmer Station LTER / palmerpenguins package") +
  scale_colour_viridis_d()
```

## Scatter Plot Enhanced
```{r}
ggplot(penguins,
       aes(x = bill_depth_mm, 
           y = bill_length_mm,
           colour = species,
           shape = species,
           size = body_mass_g,
           alpha = flipper_length_mm)) +
  geom_point() +
  scale_colour_viridis_d()
```
## Plot with facet grid facet_wrap( ~ cols) facet_grid(row ~cols)
```{r}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + 
  geom_point() +
  facet_grid(species ~ island)
```

