---
title: Professor Evaluations
author: R package build
date: '2022-02-28'
slug: professor-evaluations
categories: []
tags: []
---

## Call libraries
```{r warning=FALSE}
library("tidyverse")
library("moderndive")
library("skimr")
library("gapminder")
```

## Importing data
```{r}
evals_ch5 <- evals %>%
  select(ID, score, bty_avg, age)
```

# Data Exploration
## Initial Glimpse
```{r}
glimpse(evals_ch5)
```
### Random Sample of the data
```{r}
evals_ch5 %>%
  sample_n(size = 5)
```
### Summary Data
```{r}
evals_ch5 %>%
  summarize(mean_bty_avg = mean(bty_avg), mean_score = mean(score),
            median_bty_avg = median(bty_avg), median_score = median(score))
```
```{r}
evals_ch5 %>% select(score, bty_avg) %>% skim()
```
```{r}
plot(evals_ch5$score, evals_ch5$bty_avg)
```

### Linear correlation of score by bty_avg (two methods)
```{r}
evals_ch5 %>% 
  get_correlation(formula = score ~ bty_avg)
```
```{r}
evals_ch5 %>% 
  summarize(correlation = cor(score, bty_avg))
```


## Data visualization


```{r}
ggplot(evals_ch5, aes(x = bty_avg, y = score)) +
  geom_point() +
  labs(x = "Beauty Score", 
       y = "Teaching Score",
       title = "Scatterplot of relationship of teaching and beauty scores")
```
### With line of best fit 
```{r}
ggplot(evals_ch5, aes(x = bty_avg, y = score)) +
  geom_point() +
  labs(x = "Beauty Score", y = "Teaching Score",
       title = "Relationship between teaching and beauty scores") +  
  geom_smooth(method = "lm", se = FALSE)
```
```{r}
# Fit regression model:
score_model <- lm(score ~ bty_avg, data = evals_ch5)
# Get regression table:
get_regression_table(score_model)
```
### Get regression points
```{r}
regression_points <- get_regression_points(score_model)
regression_points
```

## Linear regression with age instead of bty_avg
```{r}
ggplot(evals_ch5, aes(x = age, y = score)) +
  geom_point() +
  labs(x = "Age", y = "Teaching Score",
       title = "Relationship between teaching and beauty scores") +  
  geom_smooth(method = "lm", se = FALSE)
```
```{r}
# Fit regression model:
score_model_age <- lm(score ~ age, data = evals_ch5)
# Get regression table:
get_regression_table(score_model_age)
```

```{r}
regression_points <- get_regression_points(score_model_age)
regression_points
```

